-- DROP TABLES
DROP TABLE Tags CASCADE CONSTRAINTS PURGE;
DROP TABLE Photos CASCADE CONSTRAINTS PURGE;
DROP TABLE Albums CASCADE CONSTRAINTS PURGE;
DROP TABLE Participants CASCADE CONSTRAINTS PURGE;
DROP TABLE User_Events CASCADE CONSTRAINTS PURGE;
DROP TABLE Education CASCADE CONSTRAINTS PURGE;
DROP TABLE Programs CASCADE CONSTRAINTS PURGE;
DROP TABLE Messages CASCADE CONSTRAINTS PURGE;
DROP TABLE User_Hometown_Cities CASCADE CONSTRAINTS PURGE;
DROP TABLE User_Current_Cities CASCADE CONSTRAINTS PURGE;
DROP TABLE Friends CASCADE CONSTRAINTS PURGE;
DROP TABLE Cities CASCADE CONSTRAINTS PURGE;
DROP TABLE Users CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE Program_ID_Seq;
